name: Validate and build
on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
    - name: Set work folder permissions    
      run: pwd && sudo chown -R $USER:$USER ./
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14.x
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm ci

  lint:
    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
          key: ${{ runner.os }}-build-
          path: |
            ~/.npm
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint
    - name: Run unit tests
      run: npm run test    

  publish-docs:
    needs: [prepare, lint]
    runs-on: ubuntu-20.04
    steps:
    - name: Publish documentation
      uses: crazy-max/ghaction-github-pages@v1
      with: 
        target_branch: gh-pages
        build_dir: docs/.vuepress/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # publish-to-npm:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - name: Publish to npm 
  #     uses: JS-DevTools/npm-publish@v1
  #     if: github.ref == 'refs/heads/master'
  #     with:
  #       token: ${{ secrets.NPM_AUTH_TOKEN }}