name: CI
on: [push, pull_request]

# on:
#   push:
#     branches:
#     - main
#   pull_request:
#     branches:
#     - main

defaults:
    runs-on: ubuntu-20.04

jobs:
  publish-docs:
    steps:
    - name: Publish documentation
      uses: crazy-max/ghaction-github-pages@v1
      with: 
        target_branch: gh-pages
        build_dir: docs/.vuepress/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-to-npm:
    steps:
    - name: Publish to npm 
      uses: JS-DevTools/npm-publish@v1
      if: github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}